### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by homps** [cbbrowne/pgcmp#10]
Any chance a license could be added to this? It's not currently clear if this is an open source contribution or not. Would also be useful to know if you'd accept PRs to fix bugs in this.

https://github.com/cbbrowne/pgcmp/blob/b71e68c17718f6c2e59390c659a6723b246b42f3/pgcmp.spec
`License:	TBD`

**Comment by cbbrowne** [comment]
Resolved, commit 9c00cb2a780ea5607456b3190f2b2019ec04fc97
