### ISSUE TITLE
False mismatch on objects permissions

### ISSUE THREAD

**Issue by rnancy** [cbbrowne/pgcmp#8]
I ran into this several times
  _
  object_type        | table permissions		
  object             | public.yyy_xxx_zzz		
  label1             | UniversalDB		
  object_definition1 | {myowner=arwdDxt/myowner	t_role=r/myowner	report=r/myowner}
  label2             | UpgradedDB		
  object_definition2 | {myowner=arwdDxt/myowner	report=r/myowner     t_role=r/myowner}
  difference_type    | mismatch		
  difference_cause   | 
_

**Comment by cbbrowne** [comment]
Yep, there are a couple places where the code coerces aclitem[] columns into text, and that's not going to order things so as to get them into compatible orders.

What we should do is to sort the aclitem[] values before coercing into text (probably!)

**Comment by cbbrowne** [comment]
Better idea...  Outright explode the acl lists into a bunch of text items using unnest().

That means that each permission becomes a separate item, and so you see which ones are missing in each direction.
